from typing import Protocol, Generator, Optional, Any, Dict, List

class IWakeWordDetector(Protocol):
    """Monitors incoming live microphone hardware buffer slices for designated activation keywords."""
    def set_wake_word(self, word: str) -> None: ...
    def scan_frame(self, audio_chunk: bytes) -> bool: ...

class ISpeechRecognizer(Protocol):
    """Processes spoken dialogue audio frames into high-accuracy transcribed textual inputs (ASR)."""
    def transcribe(self, audio_data: bytes, sample_rate: int = 16000) -> str: ...
    def parse_streaming_frame(self, chunk: bytes) -> Optional[str]: ...

class ITextToSpeech(Protocol):
    """Converts high-fidelity structural text into synthesised spoken audio tracks."""
    def synthesize(self, text: str, voice_pack: str = "zephyr", speed: float = 1.0, pitch: float = 1.0) -> bytes: ...
    def list_voice_packs(self) -> List[Dict[str, Any]]: ...

class IAudioRouter(Protocol):
    """Handles sound input pipelines, routing physical hardware, applying noise reduction filters and VAD."""
    def process_input(self, record_buffer: bytes) -> bytes: ...
    def enable_echo_cancellation(self, enabled: bool) -> None: ...
    def detect_voice_activity(self, frame: bytes) -> bool: ...
