from typing import Protocol, Dict, Any, List, Optional

class IBrowserEngine(Protocol):
    """Low-level driver handling browser contexts, viewport resizing, page instances, and tab navigation."""
    def launch(self, headless: bool = True) -> Any: ...
    def navigate_to(self, url: str) -> bool: ...
    def get_cookies(self) -> List[Dict[str, Any]]: ...
    def load_cookies(self, cookies: List[Dict[str, Any]]) -> None: ...

class IFormFiller(Protocol):
    """Enters texts and checks options within standard forms based on scraped page models."""
    def fill_form_fields(self, field_mappings: Dict[str, str]) -> bool: ...
    def solve_captcha(self, selector: str) -> str: ...

class ITransactionEngine(Protocol):
    """Regulates external automations (booking flights, comparing shops, submitting jobs) with safety approval triggers."""
    def compare_deals(self, query: str) -> List[Dict[str, Any]]: ...
    def prepare_reservation(self, service: str, details: Dict[str, Any]) -> Dict[str, Any]: ...
    def execute_secured_submit(self, checkout_payload: Dict[str, Any]) -> Dict[str, Any]: ...
